# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Menu.create(:genre => 'うどん', :name => 'ざるうどん', :price => 350, :allergy => '小麦')
Menu.create(:genre => 'うどん', :name => 'えびの天ぷら', :price => 100, :allergy => '小麦,甲殻類')
Menu.create(:genre => 'ハンバーガー', :name => 'チーズバーガー', :price => 150, :allergy => '小麦,乳')
Menu.create(:genre => 'ハンバーガー', :name => 'ナゲット', :price => 250, :allergy => '小麦')
Menu.create(:genre => 'ハンバーガー', :name => 'シェイク', :price => 100, :allergy => '乳')
Menu.create(:genre => 'ラーメン', :name => '豚骨ラーメン', :price => 700, :allergy => '小麦,卵')
Menu.create(:genre => 'ラーメン', :name => '餃子', :price => 300, :allergy => '小麦,乳')
Menu.create(:genre => 'ラーメン', :name => '唐揚げ', :price => 300, :allergy => '小麦,乳,卵')
Menu.create(:genre => 'スイーツ', :name => 'パンケーキ', :price => 450, :allergy => '小麦,乳,卵')
Menu.create(:genre => 'スイーツ', :name => 'ぜんざい', :price => 280, :allergy => '小麦')
Menu.create(:genre => '中華料理', :name => '麻婆豆腐', :price => 450, :allergy => '小麦,乳')
Menu.create(:genre => '中華料理', :name => '棒々鶏', :price => 450, :allergy => '小麦,卵')
Menu.create(:genre => '寿司', :name => 'たまご', :price => 100, :allergy => '卵')
Menu.create(:genre => '寿司', :name => 'たこの唐揚げ', :price => 300, :allergy => '小麦,卵,乳')
Menu.create(:genre => '寿司', :name => 'しょうゆ', :price => 0, :allergy => '小麦')
Menu.create(:genre => 'お好み焼き', :name => '豚玉', :price => 600, :allergy => '小麦,卵,乳')
Menu.create(:genre => 'お好み焼き', :name => 'もんじゃ焼き', :price => 450, :allergy => '小麦')
Menu.create(:genre => 'お好み焼き', :name => '豚トロ', :price => 500, :allergy => '卵')
Menu.create(:genre => 'イタリアン', :name => 'かにクリームパスタ', :price => 950, :allergy => '小麦,乳,甲殻類')
Menu.create(:genre => 'イタリアン', :name => 'マルゲリータ', :price => 600, :allergy => '小麦,乳')
Menu.create(:genre => 'イタリアン', :name => 'ティラミス', :price => 300, :allergy => '小麦,卵,乳')
Menu.create(:genre => '焼き鳥', :name => 'むね肉(たれ)', :price => 110, :allergy => '小麦')
Menu.create(:genre => '焼き鳥', :name => 'チキン南蛮', :price => 300, :allergy => '小麦,卵,乳')
Menu.create(:genre => '焼き鳥', :name => 'キャベツ', :price => 250, :allergy => '小麦')
Menu.create(:genre => 'カレーライス', :name => 'カレーライス', :price => 450, :allergy => '小麦')
Menu.create(:genre => 'カレーライス', :name => 'マンゴーラッシー', :price => 250, :allergy => '乳')
Menu.create(:genre => 'カレーライス', :name => 'ナン', :price => 500, :allergy => '小麦')
